# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim
WORKDIR /app

# Install dependencies
COPY pyproject.toml .
COPY src ./src
RUN pip install --no-cache-dir .

# Create non-root user
RUN useradd --create-home appuser
USER appuser

ENTRYPOINT ["fdp-mcp-server"]
